[package]
name = "vector-db"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "sync"] }
test-log = { version = "0.2.14", features = ["trace"] }
ndarray = { version = "0.15.6", features = ["serde"] }
anyhow = { workspace = true }
faiss = { git = "https://github.com/jondot/faiss-rs", features = ["static"] }
