[package]
name = "api-server"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
prisma-lib = { path = "../../crates/prisma"}
rspc = { workspace = true, features = ["axum"] }
specta-macros = { version = "=2.0.0-rc.1" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
prisma-client-rust = { workspace = true }
prisma-client-rust-cli = { workspace = true }
tokio = { workspace = true, features = ["full"] }
axum = "0.7.4"
