[package]
name = "api-server"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
prisma-lib = { path = "../../crates/prisma"}
rspc = { version = "0.1.3" }
serde_json = "1.0.108"
serde = { version = "1.0.193", features = ["derive"] }
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.11" }
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.11" }
