[package]
name = "prisma-lib"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
prisma-client-rust = { workspace = true }
prisma-client-rust-cli = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
