[package]
name = "file-downloader"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
tokio = { workspace = true, features = ["fs", "macros"] }
tracing = { workspace = true }
anyhow = { workspace = true }
reqwest = "0.11.24"
